name: aira
description: Aira - a smart flash card learning app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  camera: ^0.12.0+2
  flutter:
    sdk: flutter
  http: ^1.2.2
  http_parser: ^4.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
